# TEMPORARY localization-audit import.
# Exact ru-RU entity messages sourced from Lua-Frontier/Monolith-DS.
# This file is generated by Tools/sync_ru_mono_translations.py and is
# limited to entity IDs that were absent from Sector-Hex's ru-RU locale.

ent-Magazine12_gaugeUranium = барабан (12 калибр урановые)
    .desc = Барабанный магазин для патронов 12 калибра.

ent-Magazine68x52mmCaselessPractice = магазин (6,8x52мм STANAG учебные)
    .desc = Магазин, использующий учебные патроны калибра 6,8x52мм STANAG.

