# TEMPORARY localization-audit import.
# Exact ru-RU entity messages sourced from Lua-Frontier/Monolith-DS.
# This file is generated by Tools/sync_ru_mono_translations.py and is
# limited to entity IDs that were absent from Sector-Hex's ru-RU locale.

ent-120mmBulletAPHEDS = бронебойно-фугасный снаряд 120 мм

ent-150mmApheShell = бронебойно-фугасный снаряд 150 мм
    .desc = Химически разгоняемый бронебойно-фугасный снаряд для корабельных орудий калибра 150 мм. Будет работать (надеюсь).
    .ammo-loader-type = Боеприпас (бронебойно-фугасный)
    .ammo-loader-caliber = 150 мм
    .ammo-loader-weight = 17 кг

ent-220mmBulletAPHE = снаряд CYREXA 220 мм

ent-255mmBulletAPHE = снаряд Bofors 255 мм

ent-35mmBullet = 35-мм снаряд
    .desc = { ent-BaseBullet.desc }

ent-AirlockHeavyAssemblyCommand = { ent-AirlockHeavyAssembly }
    .desc = { ent-AirlockHeavyAssembly.desc }
    .suffix = Командный

ent-AirlockHeavyAssemblyEngineering = { ent-AirlockHeavyAssembly }
    .desc = { ent-AirlockHeavyAssembly.desc }
    .suffix = Инженерный

ent-AirlockHeavyAssemblyGlass = { ent-AirlockHeavyAssembly }
    .desc = { ent-AirlockHeavyAssembly.desc }
    .suffix = Стеклянный

ent-AirlockHeavyAssemblyGrey = { ent-AirlockHeavyAssembly }
    .desc = { ent-AirlockHeavyAssembly.desc }
    .suffix = Серый

ent-AirlockHeavyAssemblyPDV = { ent-AirlockHeavyAssembly }
    .desc = { ent-AirlockHeavyAssembly.desc }
    .suffix = Авангард

ent-AirlockHeavyAssemblySecurity = { ent-AirlockHeavyAssembly }
    .desc = { ent-AirlockHeavyAssembly.desc }
    .suffix = Охрана

ent-AirlockHeavyAssemblyTSFMC = { ent-AirlockHeavyAssembly }
    .desc = { ent-AirlockHeavyAssembly.desc }
    .suffix = ТСФ

ent-AirlockHeavyAssemblyUSSP = { ent-AirlockHeavyAssembly }
    .desc = { ent-AirlockHeavyAssembly.desc }
    .suffix = СССП

ent-AirlockHeavyEngineering = { ent-AirlockHeavy }
    .desc = { ent-AirlockHeavy.desc }
    .suffix = Инженерный

ent-AirlockHeavyGrey = { ent-AirlockHeavy }
    .desc = { ent-AirlockHeavy.desc }
    .suffix = Серый

ent-BulletLaserSpreadMono = energy

ent-CopperOre15 = малахит
    .suffix = 15
    .desc = { ent-CopperOre.desc }

ent-FactionLatheImmmovable = { ent-FactionLathe }
    .desc = { ent-FactionLathe.desc }
    .suffix = Неоткручиваемый

ent-LithiumOre15 = литиевая руда
    .suffix = 15
    .desc = { ent-LithiumOre.desc }

ent-Magazine12_gaugeIncendiary = барабан (12 калибр зажигательные)
    .desc = Барабанный магазин для патронов 12 калибра.

ent-Magazine68x52mmCaseless = { ent-BaseMagazine68x52mmCaseless }
    .desc = { ent-BaseMagazine68x52mmCaseless.desc }

ent-Magazine8x65mmSKRBox = SAW короб (8x65мм SKR)
    .desc = Коробчатый магазин, использующий патроны калибра 8x65мм SKR.

ent-SheetCopper1 = { ent-MaterialCopper }
    .suffix = 1
    .desc = { ent-MaterialCopper.desc }

ent-SheetCopper10 = { ent-MaterialCopper }
    .suffix = 10
    .desc = { ent-MaterialCopper.desc }

ent-SheetLithium1 = { ent-MaterialLithium }
    .suffix = 1
    .desc = { ent-MaterialLithium.desc }

ent-SheetLithium10 = { ent-MaterialLithium }
    .suffix = 10
    .desc = { ent-MaterialLithium.desc }

ent-SheetUraniumDepleted1 = { ent-SheetUraniumDepleted }
    .suffix = 1
    .desc = { ent-SheetUraniumDepleted.desc }

ent-ThrusterLargePartsT2 = { ent-ThrusterLarge }
    .suffix = T2
    .desc = { ent-Thruster.desc }

ent-WeaponCaseLongIrohSecurity = кейс с R-13 «Иерофант»
    .desc = Кейс для хранения крупнокалиберного оружия и аксессуаров к нему.

ent-WeaponTurretCharonReload = M-381 «Харон»
    .desc = Рельсовое орудие капитального класса, выпускающее массивный снаряд на экстремальной скорости и способное наносить катастрофический урон вражеским кораблям. Тяжёлый линейный ускоритель: может активироваться дистанционно или подключаться к GCS.
    .suffix = Корабельный, Ручная перезарядка, Т4

ent-WeaponTurretDravonFlak = ADBP-7 «Дравон»
    .suffix = Средний, Т2, Зенитный
    .desc = Одноствольная автопушка производства Aetherion Dynamics. Среднекалиберное орудие с высокой скорострельностью и относительно низкой отдачей, стреляет зенитными снарядами для поражения воздушных целей. Может активироваться дистанционно или подключаться к GCS.

ent-WeaponTurretVanquisherInfinite = { ent-WeaponTurretVanquisher }
    .suffix = Большой, Т4, Бесконечный
    .desc = { ent-WeaponTurretVanquisher.desc }

ent-WindowTimedSeal120Minutes = { ent-WindowTimedSeal }
    .suffix = 120 минут, Неразрушимый
    .desc = { ent-WindowTimedSeal.desc }

ent-WindowTimedSeal180Minutes = { ent-WindowTimedSeal }
    .suffix = 180 минут, Неразрушимый
    .desc = { ent-WindowTimedSeal.desc }

ent-WindowTimedSeal60Minutes = { ent-WindowTimedSeal }
    .suffix = 60 минут, Неразрушимый
    .desc = { ent-WindowTimedSeal.desc }

